version: '3.8'

services:
  web:
    build: .
#    image: vantran102/silkroadv2:latest
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: shoesql
      DB_USER: root
      DB_PASS: 123456

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shoesql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Dump2004:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
